title: "Music History with Rey"
description: "Class resources for music history at Wallowa Lake Music Camps"
baseurl: "/wallowalake"
url: "https://purple4reina.github.io"

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - "_templates/"
  - ".claude/"
